# Generated by Django 2.2.24 on 2023-03-31 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20230331_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owners_phonenumber',
            field=models.CharField(default=723434, max_length=20, verbose_name='Номер владельца'),
            preserve_default=False,
        ),
    ]
