# Generated by Django 2.2.24 on 2023-03-31 05:14

from django.db import migrations
import phonenumbers


def parse_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_pure_phone = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_flat_owners_phonenumber'),
    ]

    operations = [
        migrations.RunPython(parse_phonenumbers)        
    ]
