# Generated by Django 2.2.24 on 2023-03-31 05:28

from django.db import migrations
import phonenumbers


def parse_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_pure_phone = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(flat.owner_pure_phone):
            flat.save()

def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_pure_phone = 'None'
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20230331_0827'),
    ]

    operations = [
        migrations.RunPython(parse_phonenumbers, move_backward)          
    ]
