# Generated by Django 2.2.24 on 2023-03-31 05:45

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20230331_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owners_phonenumber', models.CharField(max_length=20, verbose_name='Номер владельца')),
                ('owner_pure_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Нормализованный номер владельца')),
                ('own_flats', models.ManyToManyField(blank=True, null=True, related_name='owned_flats', to='property.Flat')),
                ('owner', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='own', to='property.Flat', verbose_name='ФИО владельца')),
            ],
        ),
    ]
