# Generated by Django 2.2.24 on 2023-03-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20230331_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='own_flats',
            field=models.ManyToManyField(blank=True, null=True, related_name='owned_flats', to='property.Flat'),
        ),
    ]
