# Generated by Django 2.2.24 on 2023-03-31 09:38

from django.db import migrations


def fill_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()      
    for flat in flats.iterator():    
        Owner.objects.get_or_create(owner=flat.owner,
                                    owners_phonenumber=flat.owners_phonenumber,
                                    owner_pure_phone=flat.owner_pure_phone,
                                    )

def move_back(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20230331_1238'),
    ]

    operations = [
        migrations.RunPython(fill_owners, move_back)
    ]
