# Generated by Django 2.2.24 on 2023-03-31 10:10

from django.db import migrations


def make_links(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flat = Flat.objects.all()
    for Owner in Owner.objects.all():
        linked = []
        for flat in Flat.objects.all():
            if Owner.owner==flat.owner:
                linked.append(flat)
        Owner.own_flats.set(linked)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20230331_1238'),
    ]

    operations = [
        migrations.RunPython(make_links)
    ]
