# Generated by Django 2.2.24 on 2023-04-04 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20230404_0318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='complain_flat',
            new_name='flat',
        ),
        migrations.RenameField(
            model_name='complain',
            old_name='complain',
            new_name='text',
        ),
    ]
