# Generated by Django 2.2.24 on 2023-04-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20230404_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(blank=True, null=True, related_name='flat_owners', to='property.Flat'),
        ),
    ]
