# Generated by Django 2.2.24 on 2023-04-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0027_auto_20230405_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(blank=True, null=True, related_name='owners', to='property.Flat'),
        ),
    ]
